### PR TITLE
Add syntax highlighting for GettingStarted.md

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
Did I get this right, @schae234? You can check what it should look like here: https://github.com/RaoOfPhysics/Camoco/blob/add-syntax-highlighting/docs/GettingStarted.md

Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

### CODE REVIEW

**Comment by schae234** [comment]
Yes! Perfect, thanks!

**Comment by RaoOfPhysics** [comment]
I missed adding `shell` to the first code chunk. Sorry about that. If you want, I can fix it.

**Comment by RaoOfPhysics** [comment]
Oops. How did that happen? All I did was change a `.md` file…

**Comment by schae234** [comment]
coveralls can be a bit picky sometimes. There is a place to specify what gets counted in the percentage (i.e. `md` files should be ignored), but I haven't gotten around to pinpointing it yet.

**Pull request merged**
