### PR TITLE
Installation working on MacOS

### PR DESCRIPTION
**Pull request by seraco**
The installation is already working on MacOS. However, there is a problem now. The camoco script is not in the path anymore. I will keep working on this to solve this issue.

Besides, I removed some apparently unnecessary packages from the install.sh script. If they are indeed needed I will also work on including them in the final installation.

### CODE REVIEW

**Comment by seraco** [comment]
Are powerlaw and GeneWordSearch needed?

**Comment by seraco** [comment]
TravisCI is working on OSX, but the tests last a lot on this OS. Is it necessary to run tests for Python 3.4, 3.5 and 3.6? Could we skip some of them?

**Comment by schae234** [comment]
Hi @seraco 

I will move powerlaw and GeneWordSearch as dynamic imports as they are not necessary for core functionality. We can inform users that they are optional for some added functionality.

You can remove them both as requirements!

**Comment by schae234** [comment]
I think we can sacrifice older versions of python for cross platform compatibility. As I plan to leverage some of the newer features in python 3.6, lets remove support for 3.4 and 3.5.

Unless you think this is a serious mistake?

**Pull request merged**
