### PR TITLE
Overlap.py fix and linear model quick fix in COB.py

### PR DESCRIPTION
**Pull request by MeeshCompBio**
I fixed the Overlap.py script for the cli #58. The modifications are probably not the way you would have fixed it, but it will at least give you an idea of what the issue is. I also found another spot in COB.py where is calls the linear model, I converted the astype to float like I did in #56 .

### CODE REVIEW

**Comment by MeeshCompBio** [comment]
I don't think there is an option to cherry pick using the GitHub web interface so keep in mind that there is overlap here from #57 .

**Comment by schae234** [comment]
Hey @MeeshCompBio, I am glad you got this working again. Some of the changes you made to the Overlap class breaks some of the internal conventions for how Python classes work. I see what you were going for though. I sitll have to go back and look at the original bug, but I will add to this PR soon. 

:+1:  for all the PRs recently!

**Comment by MeeshCompBio** [comment]
Hi @schae234, I was totally aware the I was breaking classes with my band-aid code  :-), but I needed the CLI command to work ASAP.  If it is any consolation, @monprin ran a clean install with my fork and is running the CLI with no issues. When I have time, I will fix it the right way, but at least we have a pointer for now.

**Comment by schae234** [comment]
Not a problem at all to get things back up and running, but I probably wont merge the PR until those methods get fixed. I think there is a possibility for some wonky stuff to happen. 

Also can we open new PRs to the dev branch? I wanna keep the master branch pretty stable and keep development stuff to the dev branch. Then we can have a more reliable versioning system.

**Pull request merged**
